In [1]:
import pandas as pd

In [17]:
rest_df = pd.read_excel('제주특별자치도/제주시/식당정보/제주특별자치도_제주시_연동_식당정보_info.xlsx')
rest_df.사업장명.info()

<class 'pandas.core.series.Series'>
RangeIndex: 980 entries, 0 to 979
Series name: 사업장명
Non-Null Count  Dtype
--------------  -----
980 non-null    object
dtypes: object(1)
memory usage: 7.8+ KB

In [24]:
rest_name = rest_df.사업장명.drop_duplicates().reset_index(drop=True)
rest_name.info()

<class 'pandas.core.series.Series'>
RangeIndex: 965 entries, 0 to 964
Series name: 사업장명
Non-Null Count  Dtype
--------------  -----
965 non-null    object
dtypes: object(1)
memory usage: 7.7+ KB

In [27]:
rest_name_lst = rest_name.tolist()

In [29]:
base_frm = pd.read_excel(f'제주특별자치도/제주시/연동/{rest_name_lst[0]}_review.xlsx')

In [32]:
columns = base_frm.columns

In [34]:
all_rest_frm = pd.DataFrame(columns = columns)

In [36]:
all_rest_frm

Empty DataFrame
Columns: [리뷰, 리뷰이미지url, 작성자프로필, My플레이스, 작성자이름, 리뷰작성수, 리뷰작성일, 식당방문수, 리뷰인증방식, 식당id, 사업장명]
Index: []

In [37]:
for name in rest_name_lst :
    df = pd.read_excel(f'제주특별자치도/제주시/연동/{name}_review.xlsx')
    all_rest_frm = pd.concat([all_rest_frm , df] , axis = 0)
all_rest_frm = all_rest_frm.reset_index(drop=True)
all_rest_frm

,리뷰,리뷰이미지url,작성자프로필,My플레이스,작성자이름,리뷰작성수,리뷰작성일,식당방문수,리뷰인증방식,식당id,사업장명
0,음식은 괜찮아요 맛있게 잘먹었지만 글라스 와인은 맛이 별로였어요 ㅠㅠ 아쉽 주차도 ...,['https://search.pstatic.net/common/?autoRotat...,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/5da1f4ea8f87a842b...,쥴리지아니,"['리뷰 419', '사진 725', '팔로워 46']",2023년 5월 19일 금요일,1번째 방문,영수증,1713847517,봉플라봉뱅
1,"오랜만에 파인 다이닝을 경험 했습니다. 런치 셋 이었지만, 하나하나 정성들여 정갈하...",NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/5e8970678f87a842b...,KENNY,"['리뷰 59', '사진 56', '팔로워 3']",2023년 4월 20일 목요일,1번째 방문,예약,1713847517,봉플라봉뱅
2,웨딩촬영 뒷풀이 제대로 하고 가요!\n라구 뇨끼 스테이크 와인까지 너무맛있어요ㅠㅠ\...,['https://search.pstatic.net/common/?autoRotat...,https://search.pstatic.net/common/?autoRotate=...,https://m.place.naver.com/my/5ee02c148f87a842b...,화6494,"['리뷰 3', '사진 1']",2023년 3월 24일 금요일,1번째 방문,영수증,1713847517,봉플라봉뱅
3,음...,NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/5d8b6e098f87a842b...,win****,"['리뷰 952', '사진 10']",2023년 3월 4일 토요일,1번째 방문,예약,1713847517,봉플라봉뱅
4,지인 추천으로 예약까지 하고 귀한분들 모시고 갔는데....\n추가로 주문한 빵 4조...,NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/5d314552a34e686c9...,백록I아이오닉5I제주,"['리뷰 7', '사진 5']",2023년 2월 28일 화요일,1번째 방문,예약,1713847517,봉플라봉뱅
...,...,...,...,...,...,...,...,...,...,...,...
80529,NaN,['https://search.pstatic.net/common/?autoRotat...,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/61f8aeefbb375c124...,아그녜스,"['리뷰 214', '사진 159']",2022년 10월 4일 화요일,1번째 방문,영수증,1971746359,카페노연로117
80530,친절해요,NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/60dacc624e07bcfea...,msk****,"['리뷰 234', '사진 4']",2022년 9월 29일 목요일,1번째 방문,영수증,1971746359,카페노연로117
80531,굿,NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/6199b0727bac197ec...,김명선48,['리뷰 518'],2022년 9월 17일 토요일,1번째 방문,영수증,1971746359,카페노연로117
80532,대화하기 좋아요,NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/5e65c8948f87a842b...,한사랑은우47,"['리뷰 315', '사진 58']",2022년 9월 13일 화요일,3번째 방문,영수증,1971746359,카페노연로117
80533,굿,NaN,https://g-place.pstatic.net/assets/shared/imag...,https://m.place.naver.com/my/5ee18e458f87a842b...,kim****,"['리뷰 355', '사진 2']",2022년 5월 18일 수요일,1번째 방문,영수증,1971746359,카페노연로117

In [49]:
# all_rest_frm.columns
# all_rest_frm.My플레이스.astype('str')

In [51]:
all_rest_frm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80534 entries, 0 to 80533
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   리뷰        77509 non-null  object
 1   리뷰이미지url  31275 non-null  object
 2   작성자프로필    80472 non-null  object
 3   My플레이스    80472 non-null  object
 4   작성자이름     80472 non-null  object
 5   리뷰작성수     80472 non-null  object
 6   리뷰작성일     80472 non-null  object
 7   식당방문수     80472 non-null  object
 8   리뷰인증방식    80472 non-null  object
 9   식당id      80534 non-null  object
 10  사업장명      80534 non-null  object
dtypes: object(11)
memory usage: 6.8+ MB

In [55]:
all_rest_frm = all_rest_frm.dropna(subset=['리뷰']) # Null 값 제거
all_rest_frm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77509 entries, 0 to 80533
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   리뷰        77509 non-null  object
 1   리뷰이미지url  28735 non-null  object
 2   작성자프로필    77509 non-null  object
 3   My플레이스    77509 non-null  object
 4   작성자이름     77509 non-null  object
 5   리뷰작성수     77509 non-null  object
 6   리뷰작성일     77509 non-null  object
 7   식당방문수     77509 non-null  object
 8   리뷰인증방식    77509 non-null  object
 9   식당id      77509 non-null  object
 10  사업장명      77509 non-null  object
dtypes: object(11)
memory usage: 7.1+ MB

In [64]:
# url이 excel에선 65530개 까지가 제한
# 4분류

all_rest_frm[:20000].to_excel('제주특별자치도/제주시/식당정보/제주특별자치도_제주시_연동_리뷰전체모음_01.xlsx' , index=False)
all_rest_frm[20000:40000].to_excel('제주특별자치도/제주시/식당정보/제주특별자치도_제주시_연동_리뷰전체모음_02.xlsx' , index=False)
all_rest_frm[40000:60000].to_excel('제주특별자치도/제주시/식당정보/제주특별자치도_제주시_연동_리뷰전체모음_03.xlsx' , index=False)
all_rest_frm[60000:].to_excel('제주특별자치도/제주시/식당정보/제주특별자치도_제주시_연동_리뷰전체모음_04.xlsx' , index=False)

In [45]:
all_rest_frm.to_csv('제주특별자치도/제주시/식당정보/제주특별자치도_제주시_연동_리뷰전체모음.csv' , index=False)